/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignments;

/**
 *
 * @author Dave
 */
public class Asgn_0_MainMenu extends javax.swing.JFrame {

  /**
   * Creates new form MainMenu
   */
  public Asgn_0_MainMenu() {
    initComponents();
    this.setLocationRelativeTo(null); // center JFrame on screen;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_1_NumberAddition = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        m_btn_helloWorld = new javax.swing.JButton();
        btn_10_timeZoneClock = new javax.swing.JButton();
        btn_11_characterSheet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programming 2 - Main Menu");

        btn_1_NumberAddition.setText("1 - Number Addition");
        btn_1_NumberAddition.setToolTipText("Assignment 1 - Number Addition");
        btn_1_NumberAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1_NumberAdditionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select an Assignment to view.");

        m_btn_helloWorld.setText("3 - Hello, World!");
        m_btn_helloWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btn_helloWorldActionPerformed(evt);
            }
        });

        btn_10_timeZoneClock.setText("10 - Time Zone Clock");
        btn_10_timeZoneClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_10_timeZoneClockActionPerformed(evt);
            }
        });

        btn_11_characterSheet.setText("11 - Character Sheet");
        btn_11_characterSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11_characterSheetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_11_characterSheet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_10_timeZoneClock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m_btn_helloWorld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_1_NumberAddition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_1_NumberAddition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_btn_helloWorld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_10_timeZoneClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_11_characterSheet)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btn_1_NumberAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1_NumberAdditionActionPerformed
    Asgn_1_NumberAddition naf = new Asgn_1_NumberAddition();
    naf.setLocationRelativeTo(null);
    naf.setVisible(true);
  }//GEN-LAST:event_btn_1_NumberAdditionActionPerformed

    private void m_btn_helloWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btn_helloWorldActionPerformed
        // TODO add your handling code here:
    Asgn_3_HelloWorld hwf = new Asgn_3_HelloWorld();    // create HelloWorld form
        // hwf = hello world form
    hwf.setLocationRelativeTo(null);                    // center form on screen
    hwf.setVisible(true);                               // display HelloWorld form
    }//GEN-LAST:event_m_btn_helloWorldActionPerformed

    private void btn_10_timeZoneClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_10_timeZoneClockActionPerformed
        // TODO add your handling code here:
        Asgn_10_NewTimeZoneClock tzvf = new Asgn_10_NewTimeZoneClock();
        tzvf.setLocationRelativeTo(null);
        tzvf.setVisible(true);
        
    }//GEN-LAST:event_btn_10_timeZoneClockActionPerformed

    private void btn_11_characterSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11_characterSheetActionPerformed
        // TODO add your handling code here:
        Asgn_11_CharacterSheet csf = new Asgn_11_CharacterSheet();
        csf.setLocationRelativeTo(null);
        csf.setVisible(true);
    }//GEN-LAST:event_btn_11_characterSheetActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Asgn_0_MainMenu().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_10_timeZoneClock;
    private javax.swing.JButton btn_11_characterSheet;
    private javax.swing.JButton btn_1_NumberAddition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton m_btn_helloWorld;
    // End of variables declaration//GEN-END:variables
}
